# Generated by Django 3.1 on 2021-07-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210727_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='location_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='inventory.location'),
        ),
    ]
